#配置服务名称
spring:
  application:
    name: Master-Admin
  #    配置链路追踪
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
  # 数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #数据库url
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    # 数据库访问账户
    username: root
    # 数据库访问密码
    password: root
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                  # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                # 最大的连接数
      max-wait-millis: 60000              # 等待连接获取的最大超时时间
#端口
server:
  port: 8763

eureka:
  client:  #表示此时是客户端
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   #表示客服端向服务端进行注册，注册的地址是服务端的地址


# mapper映射文件
mybatis:
  mapper-locations: classpath:com.xd.admin/mapper/**.xml
  #定义别名
  type-aliases-package: com.xd.admin.domain
