spring:
  application:
    name: Master-Zuul
  zipkin:
    base-url: http://192.168.91.130:9411
  #    base-url: http://localhost:9411

  boot:
    admin:
      client:
        url: http://192.168.91.130:8084
#        url: http://localhost:8084
server:
  port: 8769

eureka:
  client:
    service-url:
      defaultZone: http://192.168.91.130:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/  #表示向服务注册中心注册服务

zuul:
  routes:
    api-a:
      path: /api/ribbon/**
      serviceId: hello-spring-cloud-web-admin-ribbon
    api-b:
      path: /api/feign/**
      serviceId: hello-spring-cloud-web-admin-feign  #表示网关要聚合两个服务，一个是ribbon，另一个是feign
