#配置服务名
spring:
  application:
    name: Master-Eureka
  #    链路追踪
  zipkin:
    base-url: http://192.168.91.132:9411
  boot:
    admin:
      client:
        url: http://192.168.91.132:8084
#配置服务端口
server:
  port: 8761
#配置服务注册中心
eureka:
  instance:
    hostname: 192.168.91.132
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/